import { useEffect, useMemo, useState } from 'react'
import { doc, getDoc, serverTimestamp, writeBatch } from 'firebase/firestore'
import { useNavigate } from 'react-router-dom'
import { db } from '../../firebase.js'
import { useAuth } from '../auth/AuthContext.jsx'

const days = ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت']
const defaultSchedule = days.map((_, day) => ({ day, enabled: false, start: '09:00', end: '17:00' }))
const formatDate = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const slotId = (doctorId, date, time) => `${doctorId}_${date}_${time.replace(':', '')}`

export function DoctorOnboardingPage() {
  const { user } = useAuth(); const navigate = useNavigate()
  const [form, setForm] = useState({ bio: '', fee: '', consultationDuration: 30 })
  const [schedule, setSchedule] = useState(defaultSchedule)
  const [notice, setNotice] = useState('')
  useEffect(() => { getDoc(doc(db, 'doctors', user.uid)).then((snapshot) => { if (!snapshot.exists()) return setNotice('ملف الطبيب غير موجود.'); const data = snapshot.data(); if (data.isProfileComplete) return navigate('/doctor/dashboard', { replace: true }); setForm({ bio: data.bio || '', fee: data.fee || '', consultationDuration: data.consultationDuration || 30 }); if (data.workingHours?.length) setSchedule(defaultSchedule.map((item) => { const saved = data.workingHours.find((hour) => hour.day === item.day); return saved ? { ...item, enabled: true, start: saved.start, end: saved.end } : item })) }) }, [navigate, user.uid])
  const workingHours = useMemo(() => schedule.filter((item) => item.enabled).map(({ day, start, end }) => ({ day, start, end })), [schedule])
  const updateDay = (day, values) => setSchedule(schedule.map((item) => item.day === day ? { ...item, ...values } : item))

  const save = async (event) => { event.preventDefault(); if (!form.bio || !Number(form.fee) || !workingHours.length || workingHours.some((hour) => hour.start >= hour.end)) return setNotice('أكمل البيانات وحدد يوم عمل واحدًا على الأقل بوقت صحيح.'); try { const doctorSnapshot = await getDoc(doc(db, 'doctors', user.uid)); const clinicId = doctorSnapshot.data()?.clinicId; if (!clinicId) throw new Error('MISSING_CLINIC'); const batch = writeBatch(db); const duration = Number(form.consultationDuration); const now = new Date(); for (let offset = 0; offset < 14; offset += 1) { const date = new Date(now.getFullYear(), now.getMonth(), now.getDate() + offset); const daySchedule = workingHours.find((hour) => hour.day === date.getDay()); if (!daySchedule) continue; const [startHour, startMinute] = daySchedule.start.split(':').map(Number); const [endHour, endMinute] = daySchedule.end.split(':').map(Number); for (let minutes = startHour * 60 + startMinute; minutes + duration <= endHour * 60 + endMinute; minutes += duration) { const timeSlot = `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`; batch.set(doc(db, 'availableSlots', slotId(user.uid, formatDate(date), timeSlot)), { doctorId: user.uid, clinicId, date: formatDate(date), timeSlot, status: 'available', createdAt: serverTimestamp() }, { merge: true }) } } batch.update(doc(db, 'doctors', user.uid), { bio: form.bio, fee: Number(form.fee), consultationDuration: duration, workingHours, isProfileComplete: true, updatedAt: serverTimestamp() }); batch.update(doc(db, 'users', user.uid), { isProfileComplete: true, updatedAt: serverTimestamp() }); await batch.commit(); navigate('/doctor/dashboard', { replace: true }) } catch { setNotice('تعذر حفظ الملف والمواعيد. تحقق من قواعد Firestore.') } }

  return <main className="min-h-screen bg-slate-50 p-6" dir="rtl"><form onSubmit={save} className="mx-auto grid max-w-3xl gap-5 rounded-3xl bg-white p-8 shadow-xl"><div><p className="font-bold text-teal-700">إعداد حساب الطبيب</p><h1 className="text-3xl font-bold">أكمل ملفك وحدد أوقات عملك</h1></div><label className="grid gap-2 font-bold">النبذة الطبية<textarea className="rounded-xl border p-3" rows="4" value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-bold">سعر الكشف<input className="rounded-xl border p-3" type="number" min="1" value={form.fee} onChange={(event) => setForm({ ...form, fee: event.target.value })} /></label><label className="grid gap-2 font-bold">مدة الكشف بالدقائق<input className="rounded-xl border p-3" type="number" min="15" step="15" value={form.consultationDuration} onChange={(event) => setForm({ ...form, consultationDuration: event.target.value })} /></label></div><div><h2 className="font-bold">أيام وساعات العمل</h2><p className="mt-1 text-sm text-slate-500">فعّل الأيام التي تعمل فيها، ثم حدد وقت البداية والنهاية. ستتاح مواعيد الأسبوعين القادمين.</p><div className="mt-3 grid gap-3">{schedule.map((item) => <div className="flex flex-wrap items-center gap-3 rounded-xl border p-3" key={item.day}><label className="min-w-28 font-bold"><input className="ml-2" type="checkbox" checked={item.enabled} onChange={(event) => updateDay(item.day, { enabled: event.target.checked })} />{days[item.day]}</label><label>من <input disabled={!item.enabled} className="mr-2 rounded border p-2" type="time" value={item.start} onChange={(event) => updateDay(item.day, { start: event.target.value })} /></label><label>إلى <input disabled={!item.enabled} className="mr-2 rounded border p-2" type="time" value={item.end} onChange={(event) => updateDay(item.day, { end: event.target.value })} /></label></div>)}</div></div>{notice && <p className="rounded-xl bg-amber-50 p-3 text-amber-800">{notice}</p>}<button className="rounded-xl bg-teal-700 p-3 font-bold text-white">حفظ وإتاحة المواعيد</button></form></main>
}
