import { useState } from 'react'
import { createUserWithEmailAndPassword, updateProfile } from 'firebase/auth'
import { doc, serverTimestamp, setDoc } from 'firebase/firestore'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { auth, db } from '../../firebase.js'
const schema = z.object({ fullName: z.string().min(3, 'اكتب الاسم الكامل.'), email: z.string().email('أدخل بريدًا صحيحًا.'), phone: z.string().min(7, 'أدخل رقم هاتف صحيحًا.'), password: z.string().min(8, 'كلمة المرور ٨ أحرف على الأقل.'), confirmPassword: z.string(), dateOfBirth: z.string().optional(), gender: z.enum(['female', 'male', '']).optional() }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'كلمتا المرور غير متطابقتين.' })
const errors = { 'auth/email-already-in-use': 'يوجد حساب مسجل بهذا البريد الإلكتروني.', 'auth/weak-password': 'اختر كلمة مرور أقوى.' }
export function RegisterPage() { const [notice, setNotice] = useState(''); const { register, handleSubmit, formState: { errors: formErrors, isSubmitting } } = useForm({ resolver: zodResolver(schema), defaultValues: { gender: '' } }); const submit = async (values) => { setNotice(''); try { const credential = await createUserWithEmailAndPassword(auth, values.email, values.password); await updateProfile(credential.user, { displayName: values.fullName }); await setDoc(doc(db, 'users', credential.user.uid), { uid: credential.user.uid, email: values.email, displayName: values.fullName, phone: values.phone, dateOfBirth: values.dateOfBirth || null, gender: values.gender || null, role: 'patient', isActive: true, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); await setDoc(doc(db, 'patients', credential.user.uid), { userId: credential.user.uid, fullName: values.fullName, phone: values.phone, dateOfBirth: values.dateOfBirth || null, gender: values.gender || null, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }) } catch (error) { setNotice(errors[error.code] || 'تعذر إنشاء الحساب الآن. حاول مرة أخرى.') } }; return <main className="auth-page"><form className="auth-card wide" onSubmit={handleSubmit(submit)}><a className="brand" href="/">✚ شفاء</a><div><h1>أنشئ حساب مريض</h1><p>التسجيل متاح للمرضى فقط. يُدار فريق العيادة عبر دعوات آمنة.</p></div><div className="form-grid"><label>الاسم الكامل<input {...register('fullName')} /></label><label>البريد الإلكتروني<input type="email" {...register('email')} /></label><label>رقم الهاتف<input dir="ltr" {...register('phone')} /></label><label>تاريخ الميلاد <small>اختياري</small><input type="date" {...register('dateOfBirth')} /></label><label>النوع <small>اختياري</small><select {...register('gender')}><option value="">—</option><option value="female">أنثى</option><option value="male">ذكر</option></select></label><label>كلمة المرور<input type="password" autoComplete="new-password" {...register('password')} /></label><label>تأكيد كلمة المرور<input type="password" autoComplete="new-password" {...register('confirmPassword')} /></label></div>{Object.values(formErrors).map((error) => <p className="field-error" key={error.message}>{error.message}</p>)}{notice && <p className="alert">{notice}</p>}<button className="primary" disabled={isSubmitting}>{isSubmitting ? 'جارٍ إنشاء الحساب…' : 'إنشاء حساب'}</button><p className="auth-switch">لديك حساب؟ <a href="/login">تسجيل الدخول</a></p></form></main> }
